//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teachers()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public int pin { get; set; }
        public string imya { get; set; }
        public string familya { get; set; }
        public string otchestvo { get; set; }
        public string phoneNumber { get; set; }
        public int language { get; set; }
        public int role { get; set; }
    
        public virtual Language Language1 { get; set; }
        public virtual Role Role1 { get; set; }
        public virtual TeachersPin TeachersPin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
